"""Executable regression check generation for AutoResearch.

Aggregate metrics tell the model "score is 0.8" but not *which* cases still fail
and *what* the current solution produces for them. For function-based tasks
(eval imports ``solution.py`` and runs a single-argument entry function per
case), this module turns the recorded ``metrics.json.failures`` into a concrete,
re-runnable ``.autoresearch/regression_check.py`` that re-imports the current
solution and prints per-case input / expected / actual. That deterministic
per-case feedback is what lets the model converge the last few rules instead of
guessing against an aggregate number.

The generator is intentionally conservative: it only emits a check when it can
identify a single-argument entry function from ``eval.py`` and an input field in
the failure records. Otherwise it no-ops so nothing misleading is produced.
"""

from __future__ import annotations

import json
import re
import subprocess
import sys
from pathlib import Path
from typing import Optional


# eval.py usually calls the submitted solution like ``sol.decode_text(raw)`` or
# ``mod.repair_json(raw)``. Capture the attribute name being invoked.
_ENTRY_CALL_RE = re.compile(r"\b(?:sol|mod|solution)\.([A-Za-z_]\w*)\s*\(")
# Common per-case input field names across function-based eval harnesses.
_INPUT_FIELDS = ("input", "line", "query", "raw", "text", "case", "arg")
_EXPECTED_FIELDS = ("expected", "target", "gold", "want")


def _detect_entry_function(root: Path) -> str:
    eval_path = root / "eval.py"
    if not eval_path.exists():
        return ""
    try:
        text = eval_path.read_text(encoding="utf-8", errors="replace")
    except Exception:
        return ""
    # Skip helper loaders like load_solution; prefer the most frequent call.
    counts: dict[str, int] = {}
    for name in _ENTRY_CALL_RE.findall(text):
        if name in {"loader", "load_solution"}:
            continue
        counts[name] = counts.get(name, 0) + 1
    if not counts:
        return ""
    return sorted(counts.items(), key=lambda kv: (-kv[1], kv[0]))[0][0]


def _detect_input_field(failures: list) -> str:
    for item in failures:
        if not isinstance(item, dict):
            continue
        for field in _INPUT_FIELDS:
            if field in item:
                return field
    return ""


def _detect_expected_field(failures: list) -> str:
    for item in failures:
        if not isinstance(item, dict):
            continue
        for field in _EXPECTED_FIELDS:
            if field in item:
                return field
    return "expected"


def regression_check_path(root: str | Path) -> Path:
    return Path(root) / ".autoresearch" / "regression_check.py"


def build_regression_check(root: str | Path) -> Optional[Path]:
    """Generate .autoresearch/regression_check.py from recorded failures.

    Returns the path when a check could be generated (function-based task with
    identifiable entry function, input field, and at least one recorded
    failure), else None.
    """
    root = Path(root)
    metrics_path = root / "metrics.json"
    if not metrics_path.exists():
        return None
    try:
        metrics = json.loads(metrics_path.read_text(encoding="utf-8", errors="replace"))
    except Exception:
        return None
    if not isinstance(metrics, dict):
        return None
    failures = metrics.get("failures")
    if not isinstance(failures, list) or not failures:
        return None
    # solution.py is the standard imported entry point for function-based tasks.
    if not (root / "solution.py").exists():
        return None
    entry = _detect_entry_function(root)
    input_field = _detect_input_field(failures)
    if not entry or not input_field:
        return None
    expected_field = _detect_expected_field(failures)

    cases = []
    for item in failures[:30]:
        if not isinstance(item, dict) or input_field not in item:
            continue
        cases.append({"input": item.get(input_field), "expected": item.get(expected_field)})
    if not cases:
        return None

    path = regression_check_path(root)
    path.parent.mkdir(parents=True, exist_ok=True)
    payload = json.dumps(cases, ensure_ascii=False, indent=2)
    script = (
        '"""Auto-generated per-case regression check.\n'
        "Re-runs the currently recorded failing cases against solution." + entry + ".\n"
        "Prints input / expected / actual for each so the next patch is evidence-driven.\n"
        'Regenerated by the framework after every official eval; safe to run by hand.\n'
        '"""\n'
        "import importlib.util, json\n"
        "from pathlib import Path\n"
        "CASES = json.loads(r'''" + payload + "''')\n"
        "spec = importlib.util.spec_from_file_location('solution', Path('solution.py'))\n"
        "mod = importlib.util.module_from_spec(spec)\n"
        "spec.loader.exec_module(mod)\n"
        "fn = getattr(mod, " + repr(entry) + ")\n"
        "still_failing = 0\n"
        "for i, c in enumerate(CASES):\n"
        "    try:\n"
        "        actual = fn(c['input'])\n"
        "    except Exception as e:\n"
        "        actual = 'ERROR: %s: %s' % (type(e).__name__, e)\n"
        "    ok = actual == c['expected']\n"
        "    if not ok:\n"
        "        still_failing += 1\n"
        "    print(json.dumps({'case': i, 'ok': ok, 'input': c['input'],\n"
        "                      'expected': c['expected'], 'actual': actual}, ensure_ascii=False))\n"
        "print('REGRESSION_SUMMARY still_failing=%d/%d' % (still_failing, len(CASES)))\n"
    )
    path.write_text(script, encoding="utf-8")
    return path


def run_regression_check(root: str | Path, *, timeout: float = 30.0, max_chars: int = 2600) -> str:
    """Generate + run the regression check; return its per-case output (bounded).

    Returns "" when no check could be generated. The output is a compact block
    suitable for embedding into the failure digest / execute context.
    """
    path = build_regression_check(root)
    if path is None:
        return ""
    try:
        proc = subprocess.run(
            [sys.executable, str(path)],
            cwd=str(Path(root)),
            capture_output=True,
            text=True,
            timeout=max(1.0, float(timeout)),
        )
    except Exception as exc:
        return f"(regression_check could not run: {type(exc).__name__}: {exc})"
    out = (proc.stdout or "").strip()
    if proc.returncode != 0 and not out:
        err = (proc.stderr or "").strip()[-800:]
        return f"(regression_check exited {proc.returncode}: {err})"
    if len(out) > max_chars:
        out = out[: max_chars - 40].rstrip() + "\n...<regression output clipped>...\n"
    return out


__all__ = [
    "build_regression_check",
    "regression_check_path",
    "run_regression_check",
]
